server:
  port: 3000
eureka:
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 # 清除
  instance:
    hostname: localhost
  client:
    fetch-registry: true # 不允许自己注册
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:3000/eureka
spring:
  application:
    name: eureka