server:
  port: 5000
eureka:

  instance:
    instance-id: user-1
  client:

    service-url:
      defaultZone: http://eureka3000.com:3000/eureka
spring:
  application:
    name: client-user
  zipkin:
    base-url: http://localhost:12000
  sleuth:
    sampler:
      probability: 1.0
feign:
  hystrix:
    enabled: true