server:
  port: 6000
eureka:

  instance:
    instance-id: power-0
  client:

    service-url:
      defaultZone: http://localhost:3000/eureka/
spring:
  application:
    name: service-power
  zipkin:
    base-url: http://localhost:12000
  sleuth:
    sampler:
      probability: 1.0