server:
  port: 3002
eureka:
  server:
    enable-self-preservation: false #关闭自我保护机制
    eviction-interval-timer-in-ms: 4000 # 清除
  instance:
    hostname: eureka3002.com
  client:
    fetch-registry: true # 不允许自己注册
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka3001.com:3001/eureka,http://eureka3000.com:3000/eureka
spring:
  application:
    name: eureka